// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpbeagduehxdluewzfmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwYmVhZ2R1ZWh4ZGx1ZXd6Zm1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyOTIzNzAsImV4cCI6MjA2ODg2ODM3MH0.Lb52NT9tgoynLRoR7JdFvEnlsJ-vS2yF0KuWrArCtRA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});